admins: []
forwards:
- source: https://t.me/joinchat/2mDXUO6PU0Q5OGUx
  dest: -1001730201699
  - me
  offset: 29393
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
